apiVersion: 1

datasources:
  - name: VictoriaLogs
    # ðŸ‘‡ ESTE ES EL CAMBIO CLAVE: Usamos el ID del plugin especÃ­fico de logs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victoria-logs:9428
    isDefault: true
    jsonData:
       # Ya no necesitamos "isLogs: true" porque este plugin SOLO es de logs
       maxLines: 1000