apiVersion: 1

datasources:
  - name: VictoriaLogs
    type: victoriametrics-datasource
    access: proxy
    url: http://victoria-logs:9428
    isDefault: true
    jsonData:
      # Configuración específica para Logs
      managedAlerts: false